name: Complex
on: push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Print date
        run: date
  windows:
    runs-on: windows-latest
    steps:
      - name: Print date
        run: Get-Date
  macOS:
    runs-on: macos-latest
    steps:
      - name: Print date
        run: date
  macos-11:
    needs: [ubuntu, windows, macOS]
    runs-on: macos-11
    steps:
      - name: Print date
        run: date
